# Generated by Django 4.0.4 on 2022-04-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Option Image'),
        ),
    ]
