# Generated by Django 4.0.4 on 2022-04-21 15:41

import attendance.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, verbose_name='Person name')),
                ('has_tui', models.BooleanField(default=True, verbose_name='Has TUI?')),
                ('from_college', models.BooleanField(default=False, verbose_name='Is from Ysabel?')),
                ('checkedin', models.BooleanField(default=False, verbose_name='Is inside the building?')),
                ('active', models.BooleanField(default=False, verbose_name='This ticket is active?')),
                ('qr_text', models.TextField(default=attendance.models.get_random_string, unique=True, verbose_name='QR Text label')),
                ('profile_picture', models.ImageField(blank=True, upload_to='', verbose_name='Profile picture')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Numero de puntos')),
                ('activity', models.TextField(verbose_name='Veterano')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.ticket')),
            ],
            options={
                'verbose_name': 'puntos',
                'verbose_name_plural': 'puntos',
            },
        ),
    ]
