# Generated by Django 4.0.4 on 2023-04-16 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoothPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Numero de puntos')),
                ('activity', models.TextField(verbose_name='Fotomaton')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.ticket')),
            ],
            options={
                'verbose_name': 'puntos_fotomaton',
                'verbose_name_plural': 'puntos_fotomaton',
            },
        ),
    ]
